version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/miles?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devjs_data:/var/lib/mysql
    mem_limit:  250m
#  springboot-essentials:
#    image: jeancbsan/springboot-essentials:0.0.1-SNAPSHOT
#    ports:
#      - "8081:8080"
#    environment:
#      <<: *database-variables
#    mem_limit:  512m

volumes:
  devjs_data:
